### ISSUE TITLE
[Request] Replies count for a post

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#156]
I've been always interested in how many replies a post has got. Well, this is the feature many social networks have. This enables quickly spot posts in the feed that got attention and maybe you will want to join the discussion.

So, it'd be great if a post will get a number of replies right after the View thread button.

**Comment by alicerunsonfedora** [comment]
I believe we already have a number for this available. Are you referring to a different reply number?
<img width="385" alt="Screen Shot 2020-01-20 at 14 30 59" src="https://user-images.githubusercontent.com/13445064/72752963-9be51600-3b91-11ea-9290-881d443847bf.png">

**Comment by pioneer** [comment]
Hmm yes you're right. But anyway I see some strangeness in those numbers, maybe we can convert this to a bug?

Example 1: https://hyperspaceapp-next.herokuapp.com/#/conversation/103249021067500348
The number of replies is shown as 0, though the post has 2.

Example 2: https://hyperspaceapp-next.herokuapp.com/#/conversation/103282895943672511
The number of replies is 2, but the post got about 10 replies.

**Comment by alicerunsonfedora** [comment]
The first example appears to be accurate as I did not see any replies in both Hyperspace and mastodon.social.

As for the second example, it does seem a bit weird given the replies in Hyperspace, but the Mastodon API reports that there are only two replies. I suspect that you're looking for a number that covers the entire _thread_ rather than the individual post. As the Mastodon API does not provide this number, it might be more difficult to implement this.

Please see below for the API response:
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13445064/72753674-840e9180-3b93-11ea-9efa-96702cb2201d.png">

Suffice to say, we have been running into issues with post number updates when favoriting and reblogging, but this is already marked in our issue tracker (ID: [HD-31]).

Since the data seems to be accurate as per the API, I'm going to close this issue for now.

**Comment by pioneer** [comment]
Yes, the entire number of replies in a thread, that's what I'm looking for. Ok, good it's an issue already there for that.

For the first example though, I'm wondering how can there be no replies if I can see them clearly, please have a look at the screenshots
Hyperspace: https://pasteboard.co/IQSZjOj.png
Mastodon: https://pasteboard.co/IQSZMJZ.png

**Comment by alicerunsonfedora** [comment]
I didn't see any replies on my end. Are the replies private?

**Comment by pioneer** [comment]
Didn't think about that. Yes, seems so, as the first reply has a 'lock' icon after the username. So then I'd like to include the number of private replies into the total replies count in a thread to be implemented in the issue mentioned above.

**Comment by alicerunsonfedora** [comment]
I don't think we can do that effectively since the number is pulled directly from the API on that post specifically. I'm guessing the intent is that the private reply count was excluded since that top-level post was public.

I don't think it's a necessarily good idea to display a different reply count from what the API presents. In the screenshots you provided, the reply count is still zero. I think that changing it on our end to include private reply and replies-of-replies (i.e., the entire thread) would get confusing for users, especially when they compare it to what other apps or the Mastodon website present. As such, I don't think we will implement this at this time.

**Comment by pioneer** [comment]
Well, that's reasonable unless Mastodon will change this behaviour.

Not sure what's exactly in the issue mentioned above, as I don't have access to the JIRA, but maybe it's worth to display a thread in a tree-like manner somehow? Just for the number of replies displayed to be clearly visible in the UI where it comes from. Not sure though, as in Fedilab the tree view looks ugly, and I like the simplicity of Hyperspace. A UX question, not really my area, so leaving this to you guys.

**Comment by alicerunsonfedora** [comment]
We've tried making a different layout before, but things got a little messy, so we're still working on how conversations and threads can be better represented.

**Comment by pioneer** [comment]
Now I understand what is confusing me. The replies count and the View Thread button are too distant from each other. So at first, I was thinking the number of boosts is the number of thread replies. The Reply button and the View Thread button are related to the same entity - the discussion, so maybe worth placing those buttons close to each other, to avoid such confusion.

**Comment by alicerunsonfedora** [comment]
The View Thread is intentionally placed away from the reply button as the primary quick actions on a post are either to favorite, reply, or reblog it. On mobile devices, "View thread" is moved to the mobile menu.
