### ISSUE TITLE
[Bug] Unbalanced columns in masonry layout

### ISSUE THREAD

**Issue by pioneer** [hyperspacedev/hyperspace#160]
See this screenshot https://pasteboard.co/IQYW5GTx.jpg

The leftmost and the rightmost columns have significantly more cards than the middle column, before reaching the `Load more` button.

The expected result would be a more balanced number of cards (in terms of height) in each column.

**Comment by alicerunsonfedora** [comment]
Noted in internal issue tracker as [HD-44].

**Comment by travisk-codes** [comment]
Balancing posts appears (to me) difficult to implement. Generally the masonry with more balanced column heights that I've found in the wild are of the following variety:
1. masonry bricks have similar heights, which more naturally stack. Our post heights vary a lot
2. masonry columns have equal column heights, but don't maintain post order by wrapping after columns rather than rows, which messes up chronology.
3. Avoid the problem by auto-loading bricks.

I think implementing option 3 is the way to go. Detecting scroll position may cost some, but possibly worth it if we disable the pop-in animation on posts loaded off-screen.

**Comment by alicerunsonfedora** [comment]
If there's a way that we can do it that reduces API calls and prevents us from getting 422'ed, I'd say go for it

**Comment by alicerunsonfedora** [comment]
(Of course, this should be an option in Settings but I think this one can be a on-by-default setting

**Comment by travisk-codes** [comment]
Checkout branch `HD-44` and let me know how it feels. Don't see any `422`s. Disabled post zoom effect for the time being.

**Comment by alicerunsonfedora** [comment]
I've tested the new loading in both Firefox Developer Edition and Safari, and I'm not seeing any unusual requests. Though I am noticing a couple of things:

- `PrivateRoute` was borked and essentially didn't work for some odd reason (I fixed it, though, as I realized I goofed in failing to call `userLoggedIn`; I somehow just verified the function existed instead)
- The load time seems to be a bit longer and causes parts of the UI to just disappear until the new posts load in. I noticed this behavior as well when closing the Network tab in the Inspector tools on Firefox.

On that note, I think we should start working on the following:
- Making this new loading a setting and providing a performance warning if the loading issue occurs
- Figuring out if we can display the loader indicator during these new loads
- Determining if we can call for a larger amount of posts instead of 20. The initial fetch calls for 50 posts, if I recall correctly, and I think we can cut down on the loading if we increate the fetch amount per scroll.
