### ISSUE TITLE
The static version misses the static assets.

### ISSUE THREAD

**Issue by Hukadan** [hyperspacedev/hyperspace#253]
**Describe the bug**
The static version misses the static assets.

**To Reproduce**
1. Download the static version
2. Unzip it
3. Check the static folder

**Expected behavior**
See assets (in particular js and css assets) in the static folder

**Screenshots**
Here is the actual content of the zip archive.
```
$ unzip -l Hyperspace_1.1.4_static.zip      
Archive:  Hyperspace_1.1.4_static.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     1058  10-03-2020 19:53   build/asset-manifest.json
  4765033  10-03-2020 19:52   build/background.png
      713  10-03-2020 19:52   build/config.json
    15940  10-03-2020 19:52   build/electron.js
        0  10-03-2020 19:52   build/icons/
     3431  10-03-2020 19:53   build/index.html
    13400  10-03-2020 19:52   build/logo.svg
      298  10-03-2020 19:52   build/manifest.json
      660  10-03-2020 19:53   build/precache-manifest.d2f6aff214a6ccc8c6166f7a8ad28157.js
     1183  10-03-2020 19:53   build/service-worker.js
        0  10-03-2020 19:52   build/splashes/
        0  10-03-2020 19:53   build/static/
---------                     -------
  4801716                     12 files
```
**App Information (please complete the following information):**

-   OS: OpenBSD (but I don't think it matters except that building is not possible on this platform because of Electron)
-   Version 1.1.4 but also applies to 1.1.3 (did not check further down)

Thanks

**Comment by alicerunsonfedora** [comment]
We're sorry that you're unable to use the Desktop version this way due to missing static files. We recommend using either the hosted instance at https://hyperspaceapp.herokuapp.com or downloading any of our desktop apps available. The hosted version also acts as a PWA, so if your system/browser supports using PWAs, you can use it that way. Finally, you can compile this from source directly.

I'm not sure if we're going to get to resolving this bug, as we're planning to move away from this codebase. See hyperspacedev/project#5 for details.

**Comment by Hukadan** [comment]
Thank you for your quick answer. My goal was to serve the app using nginx so I wouldn't have to run another Electron app (which is not a straightforward thing on OpenBSD to say the least).

I understand you are working on a new project and I appreciate that you responded to mu bug report nevertheless.
