### ISSUE TITLE
[Feature] Add I2p Instance

### ISSUE THREAD

**Issue by oijkhg** [hyperspacedev/hyperspace#64]
**Feature**: Add I2p Instance.
**Why?**: Mainly for better privacy and security but also to support decentralized web communications.

**Related Links**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/en/about/media

https://geti2p.net/

https://www.wikipedia.org/wiki/I2p

**Comment by alicerunsonfedora** [comment]
Is I2P a network protocol that you want implemented in Hyperspace, or is it a decentralized network?

If the former, we'll take a look into it, but this would also have to have browser support, which can be tricky since the Hyperspace desktop apps and the Hyperspace web version derive from the exact same codebase.

If the latter, as long as it support federation (eg., it's part of the fediverse), we'll definitely keep it on the radar since Hyperspace is designed to be a fediverse client (we plan to expand outwards from just Mastodon, but it can be tricky).

**Comment by alicerunsonfedora** [comment]
Issue #66 seems to have a better picture as to what this is. I'll mark this as a duplicate and close this issue.
