### ISSUE TITLE
[Feature] Add Support for Pleroma

### ISSUE THREAD

**Issue by ghbjklhv** [hyperspacedev/hyperspace#65]
**Feature**: Add Support for [Pleroma](https://pleroma.social/).
**What is Pleroma?**: [Pleroma](https://pleroma.social/) is a free software Mastadon compatible social network.

__________________________

Want to support this issue? Post a bounty on it! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by alicerunsonfedora** [comment]
Is closely related to #1 , so definitely on radar

**Comment by bleonard252** [comment]
My Pleroma instance seems to run very well on Hyperspace. The number one bug I'm running into is the About page-- it flashes a "Loading" screen then the whole page blanks. The Firefox Inspector shows an empty div.root element.

**Comment by alicerunsonfedora** [comment]
@bleonard252 I've filed your issue separately. Could you please report details on your issue there?

**Comment by bleonard252** [comment]
I'll try to handle this and #69 in [bleonard252-forks/hyperspace](/bleonard252-forks/hyperspace).

**Comment by alicerunsonfedora** [comment]
Update to Pleroma support: it appears that the "Show new posts" button doesn't appear at all on Pleroma instances, maybe due to the way timelines are streamed.

Reference: #77

**Comment by alicerunsonfedora** [comment]
Alright, so thus far, we know the following things are now working in Pleroma:

- Login and timeline viewing
- Regular performance speeds (#1)
- About page doesn't go berserk (#69)

However, it also appears that there might be a problem with timeline streaming in general with Pleroma since the timeline just populates incorrectly (#77).

**Comment by alicerunsonfedora** [comment]
The streaming issue from my initial tests appears to be a problem with Pleroma not having streaming in this manner rather than an issue with Hyperspace. Attempting to switch to WebSockets also causes some issues on the browser side of things, namely due to the way Megalodon seems to handle them.

I'm guessing that streaming via HTTPS will make it to Pleroma sooner or later, but it appears as if other important features work just fine. For now, I'm going to mark this as complete.
